# Generated by Django 2.1.15 on 2022-02-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='absract',
            new_name='abstract',
        ),
    ]
