# Generated by Django 2.1.15 on 2022-02-13 15:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220213_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfile',
            name='file',
            field=models.FileField(upload_to=core.models.get_studyfile_path),
        ),
    ]
