# Generated by Django 2.1.15 on 2022-02-13 17:03

import core.models
from django.db import migrations, models
import study.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220213_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyfile',
            name='size_kb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studyfile',
            name='file',
            field=models.FileField(upload_to=core.models.get_studyfile_path, validators=[study.validators.FileValidator()]),
        ),
    ]
