# Generated by Django 2.1.15 on 2022-02-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220213_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfile',
            name='size_kb',
            field=models.FloatField(),
        ),
    ]
